//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Context : DbContext
    {
        public Context()
            : base("name=Context")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_CUADRILLA> t_CUADRILLA { get; set; }
        public virtual DbSet<t_CUADRILLA_ZONA> t_CUADRILLA_ZONA { get; set; }
        public virtual DbSet<t_HISTORICO_ESTADO_RECLAMO> t_HISTORICO_ESTADO_RECLAMO { get; set; }
        public virtual DbSet<t_PUNTO> t_PUNTO { get; set; }
        public virtual DbSet<t_RECLAMO> t_RECLAMO { get; set; }
        public virtual DbSet<t_TIPO_RECLAMO> t_TIPO_RECLAMO { get; set; }
        public virtual DbSet<t_USUARIO> t_USUARIO { get; set; }
        public virtual DbSet<t_ZONA> t_ZONA { get; set; }
        public virtual DbSet<Reportes> Reportes { get; set; }
    }
}
