//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_CUADRILLA_ZONA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_CUADRILLA_ZONA()
        {
            this.t_RECLAMO = new HashSet<t_RECLAMO>();
            this.t_RECLAMO1 = new HashSet<t_RECLAMO>();
        }
    
        public long IDCuadrilla { get; set; }
        public long IDZona { get; set; }
    
        public virtual t_CUADRILLA t_CUADRILLA { get; set; }
        public virtual t_ZONA t_ZONA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_RECLAMO> t_RECLAMO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_RECLAMO> t_RECLAMO1 { get; set; }
    }
}
