//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_PUNTO
    {
        public long ID { get; set; }
        public long IDZona { get; set; }
        public double Latitud { get; set; }
        public double Longitud { get; set; }
    
        public virtual t_ZONA t_ZONA { get; set; }
    }
}
