//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_CUADRILLA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_CUADRILLA()
        {
            this.t_CUADRILLA_ZONA = new HashSet<t_CUADRILLA_ZONA>();
        }
    
        public long ID { get; set; }
        public string Nombre { get; set; }
        public string Encargado { get; set; }
        public short CantidadPeones { get; set; }
        public string Observaciones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_CUADRILLA_ZONA> t_CUADRILLA_ZONA { get; set; }
    }
}
